### ISSUE TITLE
Supports 7040?

### ISSUE THREAD

**Issue by Riz-waan** [zearp/OptiHack#13]
Sorry for opening an issue, but I was wondering if this is the same for a 7040?

**Comment by zearp** [comment]
Won't work. The 7040 series uses 6th gen Intel Skylake. Shouldn't be impossible or too hard though. 

Start here: https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html

**Comment by Riz-waan** [comment]
Okay thank you, but would all the kexts and stuff be the same. I am mostly concerned with bios settings

**Comment by zearp** [comment]
The base kexts are about the same for any build, the config and ACPI patches will be different. As for the BIOS, you don't have to deal with anything like UEFI shells if you use OpenCore's quirks to skip doing things like DVMT and CFG Lock.

Be prepared to experiment with config and BIOS settings like legacy mode to fix sleep. Start with the guide I linked. It is the best starting point to learn and get your build working with OpenCore.

I would also check how others with your computer configured things in OpenCore or Clover. As far as I can tell the process is similar to 7020. Try to boot with [this](https://github.com/optiplex-osx/Dell-OptiPlex-7040-Clover-EFI) and if it works migrate it to OpenCore and learn step by step each part of the config and check each of those. It's fun!
