### ISSUE TITLE
layout-id for audio should be 13

### ISSUE THREAD

**Issue by 2b2bff** [zearp/OptiHack#17]
At least on my OptiPlex 7020 MT it is the best. I don't know whether internal speaker does work, because I don't use it, but it can differ between "line-out" and "headphones", what 15 can not.

**Comment by mgrimace** [comment]
ID=13 enables front and rear as above, but disables system audio (+front, +back, -system). Depends on individual use case, but for me the current setting of ID=16 is best (+front, +system, -back). @zearp added info in the readme for users to customize this value for their own use case

**Comment by zearp** [comment]
Thanks! I will check it out.

With layout 13 it loses auto-sensing but it does all you to manually switch between front headphone and line-out in the back. Forgot to check internal speaker functionality.

With layout 15 it auto-senses both front and back, but only changes name when front port is used for the rear port is shows as internal. Internal speaker itself doesn't work anymore.

With layout 16 it auto-senses when headphones are plugged in, default is internal speaker. I think layout 16 is the closest as auto-sensing works. Just the back ports aren't configured properly.

It's kind of mystery (to me) how exactly these layouts work. This is also the only layout I found so far that shows the ports in a graphical way in Hackintool. It may be more than just cosmetic. I think the best course of action is to create a new layout based on 16 where the ports on the back work. I did some [information gathering](https://github.com/zearp/OptiHack/blob/master/text/Audio_Codecs.md) which could be helpful.

My guess is that the MT and SFF models don't use the same audio port layout. I know 16 is based on the 9020 SFF. I wish all this had some more up-to-date documentation somewhere. Would be nice to make some layouts form scratch that work for MT and SFF 7020/9020 models.

@2b2bff 
If you got time can you gather the output ```cat /proc/asound/card0/codec#0 ``` on Linux? also check for other cards like card1 and other codecs in the card folders. On mine I had two, one was hdmi and other on-board. I wonder how much different the 7020 MT is vs my SFF. Thanks!

**Comment by zearp** [comment]
Thanks! I will check it out.

With layout 13 it loses auto-sensing but it does allow you to manually switch between front headphone and line-out in the back. Forgot to check internal speaker functionality.

With layout 15 it auto-senses both front and back, but only changes name when front port is used for the rear port is shown as internal. Internal speaker itself doesn't work anymore.

With layout 16 it auto-senses when headphones are plugged in, default is internal speaker. I think layout 16 is the closest, just the back ports aren't configured properly.

It's kind of mystery (to me) how exactly these layouts work. This is also the only layout I found so far that shows the ports in a graphical way in Hackintool. It may be more than just cosmetic. I think the best course of action is to create a new layout based on 16 where the ports on the back work. I did some [information gathering](https://github.com/zearp/OptiHack/blob/master/text/Audio_Codecs.md) which could be helpful.

My guess is that the MT and SFF models don't use the same audio port layout. I know 16 is based on the 9020 SFF. I wish all this had some more up-to-date documentation somewhere. Would be nice to make some layouts from scratch that work for MT and SFF 7020/9020 models.

@2b2bff 
If you got time can you gather the output ```cat /proc/asound/card0/codec#0 ``` on Linux? Please also check for others like card1 and other codec#x files too in the card folders. On mine I had two, one was hdmi and other on-board. I wonder how much different the 7020 MT is vs my SFF. Thanks!

**Comment by davidAlaBer** [comment]
Hello! First of all thanks for this guide @zearp and contributors.
I am new at Github.
I succeed installing Catalina in a 9020 MT, multi boot with Windows (using an old iMac as target display through DP to miniDP) :)

One issue:
-Mic front jack is not working in my built. 

I will keep reporting.  I want to tell you here I am for your required guided tests in my 9020 mt i5 4590 to improve the guide.

Off-topic:
Can't map USB internal port because I have no such device at the moment (I am waiting for a Broadcom wifi/bt card, maybe with it I could do it), any suggestion?

**Comment by zearp** [comment]
@davidAlameda No need to map the internal port if its not showing up, map it once it has something connected. As for the audio layout, a new has been made here; https://github.com/zearp/OptiHack/pull/15#issuecomment-676709795

Feel free to test it out on your MT and report your findings.

Big thanks to pkendall64.
