### ISSUE TITLE
Graphic card not recognised

### ISSUE THREAD

**Issue by davidAlameda** [zearp/OptiHack#18]
Hi!
I read this:
'dGPU
The current config disables any external graphics cards, this is to prevent issues. Once the iGPU is working properly you can start setting up external graphics. Don't forget to remove the -wegnoegpu and if the dGPU uses HDMI also the -igfxnohdmi boot flags.'

I can't find them.
rx 580 sapphire GPU is not recognised.

Any idea?

**Comment by zearp** [comment]
Yes, thanks for bringing this up! I totally forgot I moved the boot flags to the device sections where possible. 

Just remove the ```disable-external-gpu``` key from the device section under ```PciRoot(0x0)/Pci(0x2,0x0)```. If you don't plan on using iGPU at all you can remove the whole block to automatically configure the iGPU for computing tasks only. But I don't know if that's what you want.

Let me know if removing that flag solves it.

**Comment by davidAlameda** [comment]
Hi! 
Thanks for the quick reply I am working on it right now.

Deleting the entry didn't work :(
My Rx 580 card have displayport and hdmi. I use displayport: black screen.

I tried deleting Nvram but nothing changed.

**Comment by zearp** [comment]
That's odd. The only thing that disabled external graphics was that ```disable-external-gpu``` property. If you didn't add any new SSDTs or stuff then it should work. But I have no cards here to test myself. Is it enabled in the BIOS? I also recall someone else saying that they needed to change graphics order in the BIOS to get external to work but I may misremember that. Can't hurt to check and try though.

**Comment by davidAlameda** [comment]
It is funny that Bios says my card is an ATI radeon, when it is a Amd Rx 580, it us supposed to work natively in Osx. Neither work selecting it in Bios

**Comment by zearp** [comment]
I guess the BIOS still has some old vendor id names in there. AMD took over ATI so that should be fine, just cosmetic.

Really no clue as to why it's not working, specially since it natively supported. I'm sure you got the cable connected to the right port and that it works in BIOS and other OS's. I read in the buyers guide some brands have issues (XFX, PowerColour, HIS and VisionTek) and may require flashing the VBIOS of the card.

I can't think of anything that would prevent it from showing up. There's no patches or other settings that do anything related to this. I'll try to see if I can find a card to test with but chances are it won't be an RX580. It has to be cheap as I won't really use it, my only motivation is to use iGPU for computing to relieve the CPU/dGPU.

Sorry I can't be of more help. Did you check the boot log for anything related to this? Maybe there's some error or message that could help. I did find some similar issues with the RX580 where it doesn't show up. 

What is the vendor and device id of your card?

**Comment by davidAlameda** [comment]
I didnt change any ssdt or any stuff (only a new portmap, now usb internal works with fenvi bt+wifi card)

FYI
When I boot selecting iGpu in bios, I can see Rx 580 (dGpu)in system profiler.
AMD (0x1002)
Device 0x67df
Metal compatible

**Comment by pkendall64** [comment]
I have a Yeston RX 550 640SP which is a Baffin based board i.e. device-id 0x67ff and I have it working well.
I did what @zearp has said in the latest update to the README and removed the PCI section for the iGPU. I also had to select the AMD card in the BIOS as primary (which btw is always printed as ATI Radeon in the BIOS).
Once I did this I got hardware video decode working. Funny how we seem to end up doing the same thing at the same time.
The only problem I have with my video card is after sleep, but I just disabled that for the moment.

**Comment by pkendall64** [comment]
@davidAlameda My card has HDMI and DVI. I used the HDMI connector and all is good. Can you try the HDMI rather than the DP connector?

**Comment by zearp** [comment]
Is the info displayed in the PCI section correct? It should show correct VRAM size and which kext is loaded and stuff like that. I know some others used dGPU with this setup just fine but I don't know which cards they used.

If you don't have any of the "dodgy" brands listed in the buyers guide and everything else shows up fine then I really have no more ideas other than scouring logs and trying debug builds of OC/WEG/etc for even more logs to scour.

Hopefully @pkendall64's suggestions help as well.

**Comment by davidAlameda** [comment]
> @davidAlameda My card has HDMI and DVI. I used the HDMI connector and all is good. Can you try the HDMI rather than the DP connector?

:( no hdmi output

**Comment by pkendall64** [comment]
@davidAlameda there are others that have had problems with RX580's on other hacks not recognising the card.
Specifically https://www.reddit.com/r/hackintosh/comments/dr287e/rx_580_not_detected_catalina/ seems to be a problem.
If you have windows you could check that it's not a 2048SP version which means it's really a RX570.

Others get a black screen and this seems to fix it for them https://www.tonymacx86.com/threads/solved-sapphire-rx-580-nitro-se-black-screen-on-hdmi-and-dvi.267078/page-4#post-1906898 you will have to figure out how to do that with OpenCore, but I think it's a patch in `Kernel > Patch` that you need to do.

**Comment by davidAlameda** [comment]
> @davidAlameda there are others that have had problems with RX580's on other hacks not recognising the card.
> 
> Specifically https://www.reddit.com/r/hackintosh/comments/dr287e/rx_580_not_detected_catalina/ seems to be a problem.
> 
> If you have windows you could check that it's not a 2048SP version which means it's really a RX570.
> 
> 
> 
> Others get a black screen and this seems to fix it for them https://www.tonymacx86.com/threads/solved-sapphire-rx-580-nitro-se-black-screen-on-hdmi-and-dvi.267078/page-4#post-1906898 you will have to figure out how to do that with OpenCore, but I think it's a patch in `Kernel > Patch` that you need to do.

My gpu is Sapphire rx 580 8gb pulse. No idea, it's used. Maybe it is faulty. I checked with Windows os (without opencore) and it doesn't have any output. So... it is strange it appears in osx system profiler.

**Comment by pkendall64** [comment]
@davidAlameda You may have to flash your card with EFI firmware, if it is used it may have been used for mining in which case it may have firmware on it that does not use the display connectors. You can download firmware from https://www.techpowerup.com/vgabios/
https://www.techpowerup.com/vgabios/?architecture=AMD&manufacturer=Sapphire&model=RX+580&interface=&memType=&memSize=&since=
Use the GPU-Z tool before changing the firmware to check it before hand. You should make a backup of the firmware before flashing a new version.

**Comment by mgrimace** [comment]
> I have a Yeston RX 550 640SP which is a Baffin based board i.e. device-id 0x67ff and I have it working well.

Can I ask about your experience with the Yeston? I'm debating going graphics card vs., wifi/bt in the single free PCIe slot on the SFF. Have you tried any light gaming with the Yeston, dual-boot, and/or do you find it helpful in any other ways? I'm not sure which would be the better QOL improvement!

**Comment by zearp** [comment]
@mgrimace Why not both? I use the tiny 1x slot for bt/wifi. Leaving the faster slot free. The max speed of the 1x is 500MB/s, enough for 1gbit wifi.

**Comment by zearp** [comment]
@davidAlameda What @pkendall64 said about the card possibly being configured for mining makes a lot of sense. It would also explain why you can see it under PCI but not see any video output. Much more likely than some odd hardware or software problem. Flashing VBIOS can be daunting but since it doesn't work in Windows and if you can't return it then you don't have much to lose. I hope flashing it will sort the card out!

**Comment by pkendall64** [comment]
@mgrimace The Yeston works really well. I play Liftoff Drone Racing on it at 1720x720 resolution and it keeps about 30fps.
If you get a Yeston 550 make sure you get one that has id 0x67ff so it has to be a baffin core, i.e. Polaris 21. I got mine from Banggood. I also got a fenvi FV-HB1200 and I have both in the 9020SFF as the Yeston is single slot half height.

The only problem I have is that after sleep the video is the top 640x480 centred on the display and alternating flashing white.
So I have disabled sleep.

**Comment by mgrimace** [comment]
> @mgrimace Why not both? I use the tiny 1x slot for bt/wifi. Leaving the faster slot free. The max speed of the 1x is 500MB/s, enough for 1gbit wifi.

I had no honest idea I could do both, thanks for that!

> @mgrimace The Yeston works really well. I play Liftoff Drone Racing on it at 1720x720 resolution and it keeps about 30fps.

Great thanks, I was thinking for some light gaming myself and that sounds perfectly reasonable.

> If you get a Yeston 550 make sure you get one that has id 0x67ff so it has to be a baffin core, i.e. Polaris 21. I got mine from Banggood. I also got a fenvi FV-HB1200 and I have both in the 9020SFF as the Yeston is single slot half height. I'm using a 3440x1440 UWQHD screen and it's really nice.

Appreciate the advice and experience on both cards, I didn't realize the Fenvi HB1200 would fit in the little slot! Interesting about sleep though with the Yeston. I read a bit about it on some forums and it seemed like it was pretty well the best option for the SFF (size and not needing a new PSU). Much appreciated, looks like the next step is hardware tinkering!

**Comment by davidAlameda** [comment]
@zearp @pkendall64 thanks for the solutions and advices. I will return the graphic card and I have learned not to buy refurbished gpus ;)
Flashing it is daunting for me and the risk is higher.
I want 4k and I will use the card for video/fx editing and some graphic design, any cheap suggestion instead rx 580 for a 9020 mt?

**Comment by pkendall64** [comment]
@davidAlameda Um, yeah, get one of the Yeston RX550 from banggood. Just make sure thats it's a Polaris 21 based unit.
https://www.banggood.com/Yeston-RX550-4GD5-LP-4GB-GDDR5-128Bit-1071MHz-6000MHz-Gaming-Graphics-Card-for-Video-p-1581210.html?rmmds=search&cur_warehouse=CN
The 2GB ones are Lexa core and will not work in Mac OS. Only the Baffin core (Polaris 21) units will work. They are normally differentiated by saying 640SP (Stream Processors).

**Comment by davidAlameda** [comment]
> @davidAlameda Um, yeah, get one of the Yeston RX550 from banggood. Just make sure thats it's a Polaris 21 based unit.
> https://www.banggood.com/Yeston-RX550-4GD5-LP-4GB-GDDR5-128Bit-1071MHz-6000MHz-Gaming-Graphics-Card-for-Video-p-1581210.html?rmmds=search&cur_warehouse=CN
> The 2GB ones are Lexa core and will not work in Mac OS. Only the Baffin core (Polaris 21) units will work. They are normally differentiated by saying 640SP (Stream Processors).

It's very nice!

**Comment by davidAlameda** [comment]
> @mgrimace The Yeston works really well. I play Liftoff Drone Racing on it at 1720x720 resolution and it keeps about 30fps.
> If you get a Yeston 550 make sure you get one that has id 0x67ff so it has to be a baffin core, i.e. Polaris 21. I got mine from Banggood. I also got a fenvi FV-HB1200 and I have both in the 9020SFF as the Yeston is single slot half height. I'm using a 3440x1440 UWQHD screen and it's really nice.
> 
> The only problem I have is that after sleep the video is the top 640x480 centred on the display and alternating flashing white.
> So I have disabled sleep.

New card and it works fine! I have the same problem with my new graphic card rx 570 8gb. I have disabled it for the moment like you did. Weird.

**Comment by pkendall64** [comment]
@davidAlameda Glad to hear you've got it going. Hopefully if we both ask on different forums we can find out what the problem is. I'll let you know if I come across a fix.

**Comment by davidAlameda** [comment]
I hope so. I will search as well. Another weird thing is after disabling sleep. I thought to enable a screensaver and I left, after 1 hour I found the machine hot like hell 68 degrees and all fans spinning like crazy. Why?

**Comment by pkendall64** [comment]
I've not seen that problem. If it does it again you will need to look to see what applications are running.

**Comment by zearp** [comment]
@davidAlameda Some of the newer macOS screensavers are very heavy on the CPU/GPU so it will heat up fast. Specially the Drift one. Try using the good old Flurry or the Apple logo with text set to blank, that one barely has any impact on the system load. Personally I stopped using screen savers and just have the screen turn off after 30 minutes.

As for the sleep issues, I wonder what could be causing it. With the iGPU setup as compute thingy WEG is most likely not doing anything anymore, that would leave the Apple driver that's failing. Need to figure out what the sequence is when you wake the machine up. It's very peculiar the screen is sort of woken up properly but set to the wrong resolution/mode. Anything useful in the logs?

Maybe pacthing/injecting ECID could help? Hackintool has a little helper for it but it probably won't do the trick.

**Comment by davidAlameda** [comment]
When it wakes up the resolution is low 640x480 and it flickrrs. I guess it doesnt respond. Bios is set to auto. I didn't add any new kext. Any idea?

**Comment by davidAlameda** [comment]
> @davidAlameda Some of the newer macOS screensavers are very heavy on the CPU/GPU so it will heat up fast. Specially the Drift one. Try using the good old Flurry or the Apple logo with text set to blank, that one barely has any impact on the system load. Personally I stopped using screen savers and just have the screen turn off after 30 minutes.
> 
> 
> 
> As for the sleep issues, I wonder what could be causing it. With the iGPU setup as compute thingy WEG is most likely not doing anything anymore, that would leave the Apple driver that's failing. Need to figure out what the sequence is when you wake the machine up. It's very peculiar the screen is sort of woken up properly but set to the wrong resolution/mode. Anything useful in the logs?
> 
> 
> 
> Maybe pacthing/injecting ECID could help? Hackintool has a little helper for it but it probably won't do the trick.

Is it possible to be related with CSM is enabled in bios? When I boot with dGPU and NO verbose the resolution is wrong and low. I can't fix it via config.plist
How can I disable CSM if i disable legacy rom boot opencore is gone? Any expert?

**Comment by pkendall64** [comment]
@davidAlameda I had problems similar to what you are saying when I had the BIOS setting to Auto for the graphics card. To get the dGPU working correctly and using the iGPU as a hardware decoder/encoder I had to set the BIOS to "ATI Radeon" or whatever it was for dGPU. In my setup I have no verbose and I have the apple logo and boot chime working. The Apple logo is the wrong resolution, but after a while it changes to the correct resolution just before the login screen.

About the CSM, I have no idea if thats even possible with one of these machines.

**Comment by davidAlameda** [comment]
In my setup I have no verbose and I have the apple logo and boot chime working as well.  I find some info about GPO flashing the dGPU and CSM disabled to fix it but is too experimental for me, to be honest. 
I also found that CSM is enabled with Dell UEFI :(

I wonder if the wrong resolution at waking up  (after SLEEP) is related to it.

**Comment by davidAlameda** [comment]
Nice! I disabled Legacy rom boot option in bios and now boot resolution is correct and not distorted. @pkendall64 @zearp

**Comment by davidAlameda** [comment]
Now I have a black screen when I try to wake up the machine after SLEEP

System-wide power settings:
 SleepDisabled		0
Currently in use:
 standby              0
 Sleep On Power Button 1
 womp                 1
 hibernatefile        /var/vm/sleepimage
 powernap             1
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                2 (sleep prevented by useractivityd, sharingd)
 autopoweroffdelay    259200
 hibernatemode        0
 autopoweroff         0
 ttyskeepawake        1
 displaysleep         2
 highstandbythreshold 50
 standbydelaylow      86400

**Comment by davidAlameda** [comment]
System Sleep Wake had a problem:

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 17s



Process:          swd [270]
Architecture:     x86_64
Footprint:        372 KB
Start time:       2020-09-08 01:37:23 +0200
End time:         2020-09-08 01:37:23 +0200
Num samples:      1 (1)

  Thread 0x860    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 109769) [0x7fff72cdecc9] 1
    1  ??? [0x1013f7454] 1
      1  ??? [0x1013f71dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff72e402b6] 1
         *1  ??? [0xffffff80002c1206] 1
           *1  ??? [0xffffff8000984c37] 1
             *1  ??? [0xffffff800089d7c1] 1
               *1  ??? [0xffffff80002e49e7] (running) 1

  Binary Images:
        0x7fff72cc4000 -     0x7fff72cfafff  libdyld.dylib (750.6)               <789A18C2-8AC7-3C88-813D-CD674376585D>  /usr/lib/system/libdyld.dylib
        0x7fff72e1f000 -     0x7fff72e4bfff  libsystem_kernel.dylib (6153.141.1) <2B6311E6-6240-3EF7-8C87-475B66F7452C>  /usr/lib/system/libsystem_kernel.dylib

**Comment by pkendall64** [comment]
@davidAlameda I did the same and disabled "Legacy boot rom support" an I too get the black screen with exactly the same crash. Nice that the resolution is right during the boot phase though. I did read somewhere about disabling serial ports in the BIOS, but that didn't fix the problem for me. I'll keep searching.

**Comment by zearp** [comment]
Disabling legacy roms breaks sleep. This has been the case in a lot of Dell systems. Including Latitude laptops.

It will require ACPI patches and I’ve never managed to get it sorted. Legacy roms does some magic.

**Comment by davidAlameda** [comment]
Sleep is unusable with dGPU (Yeston or RX 570) so disabling legacy rom is at least nicer for the moment ;)

**Comment by zearp** [comment]
@davidAlameda I think you're missing some boot args to get more detailed crash logs. Try adding ```keepsyms=1 debug=0x100``` and check is ApplePanic is set to yes. Then trigger the panic again, the report should now contain more information.

I tried figuring out what exactly legacy roms does that makes sleep work but I wasn't' successful. If we know exactly what it does we can make some ACPI patches to sort it out. I've tried many BIOS settings, disabled so much and sleep never worked properly with legacy roms disabled.

**Comment by zearp** [comment]
@davidAlameda I think you're missing some boot args to get more detailed crash logs. Try adding keepsyms=1 debug=0x100 and check if ApplePanic is set to yes. Then trigger the panic again, the report should now contain more information.

I tried figuring out what exactly legacy roms does that makes sleep work but I wasn't' successful. If we know exactly what it does we can make some ACPI patches to sort it out. I've tried many BIOS settings, disabled so much and sleep never worked properly with legacy roms disabled.

**Comment by davidAlameda** [comment]
Done!

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        debug=0x100 keepsyms=1 chunklist-security-epoch=0 -chunklist-no-rev2-dev
Time Awake Since Boot: 17s


Process:          swd [269]
Architecture:     x86_64
Footprint:        388 KB
Start time:       2020-09-08 15:19:23 +0200
End time:         2020-09-08 15:19:23 +0200
Num samples:      1 (1)

  Thread 0x7e4    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 109769) [0x7fff714d1cc9] 1
    1  ??? [0x10bd63454] 1
      1  ??? [0x10bd631dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff716332b6] 1
         *1  ??? [0xffffff80002c1206] 1
           *1  ??? [0xffffff8000984c37] 1
             *1  ??? [0xffffff800089d7c1] 1
               *1  ??? [0xffffff80002e49e7] (running) 1

  Binary Images:
        0x7fff714b7000 -     0x7fff714edfff  libdyld.dylib (750.6)               <789A18C2-8AC7-3C88-813D-CD674376585D>  /usr/lib/system/libdyld.dylib
        0x7fff71612000 -     0x7fff7163efff  libsystem_kernel.dylib (6153.141.1) <2B6311E6-6240-3EF7-8C87-475B66F7452C>  /usr/lib/system/libsystem_kernel.dylib

**Comment by davidAlameda** [comment]
Model: iMac15,1, BootROM 235.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 3,3 GHz, 16 GB, SMC 2.22f16
Graphics: Radeon RX 570, Radeon RX 570, spdisplays_pcie_device, 8 GB
Memory Module: DIMM3, 4 GB, DDR3, 1600 MHz, Hynix/Hyundai, HMT451U6AFR8C-PB
Memory Module: DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 8JTF51264AZ-1G6E1
Memory Module: DIMM4, 4 GB, DDR3, 1600 MHz, Hynix/Hyundai, HMT451U6AFR8C-PB
Memory Module: DIMM2, 4 GB, DDR3, 1600 MHz, Micron, 8JTF51264AZ-1G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.1)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: KINGSTON SV300S37A120G, 120,03 GB
Serial ATA Device: SAMSUNG SSD PM851 2.5 7mm 256GB, 256,06 GB
Serial ATA Device: TSSTcorp DVD-ROM SH-116CB
Serial ATA Device: WDC WD5000AADS-00S9B0, 500,11 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
Thunderbolt Bus:

**Comment by zearp** [comment]
@davidAlameda I don't see any differences, its going to be very hard figuring out what exactly is going on/wrong with so little info about why the kernel is crashing. I've checked around town for a graphics card to do some testing too but can't find anything that would be supported or at a reasonable price.

Did you also check the log files? Could have some more info. I would note the current time, clear the logs then trigger the panic and reboot. The logs should then just contain what happened right before the crash and the reboot, knowing the time is useful for finding the right spots. It might be useless though but I can't think of anything else atm.

**Comment by davidAlameda** [comment]
Hello again @zearp and @pkendall64 

I took a look at the log as you told me. I couldn't find nothing at all (forgot to save it). In fact there is no crash. Something has changed, when it wakes (legacy enabled), the display is full of colours and glitches (before it was 640x480 and readable). I share the screen from a real mac and it was fine, no crash.

@pkendall64 could you make any test with your dGpu?

**Comment by pkendall64** [comment]
@davidAlameda My system does exactly the same as yours. I have not tried flipping back to legacy enabled as I'm out of town till Sunday.

**Comment by davidAlaBer** [comment]
Hi @pkendall64 
Any update on this topic?

**Comment by pkendall64** [comment]
Not using this system any more. I upgraded to a newer system.
