### ISSUE TITLE
Stable EFI (24102020) v2.5 feedback

### ISSUE THREAD

**Issue by davidAlaBer** [zearp/OptiHack#24]
Hi!
-Bluetooth not working after update (I copied my working usb map kext). Do I need to map USB again? (I guess internal USB is gone)
-No graphical picker (I also copied needed drivers that was already working before)
I went back to my v2.5 EFI for the moment.

@Zearp Any important reason to update? I miss some news or explanation on the v2.5 new release improvements.

Thanks!

**Comment by zearp** [comment]
It's weird that your bluetooth and existing usb map doesn't work. You should be able to copy it and use it. The only changes are newer versions of OpenCore and the kexts used. So your internal USB port should still be mapped if you copied your port map over. You can check in Hackintool what's connected to the USB ports.

I find it really weird that when using your own port map your internal USB port used for bluetooth is no longer working. Maybe you forgot to copy the kexts needed for bluetooth? Cuz if you're using your own map and there's no internal USB port showing in Hackintool then that would imply a new version of a kext breaks usb somehow which is very unlikely and I wouldn't even know which kext would be responsible for it. We don't use any usb kexts other than a map (which is a text file that just lists the ports and it's h/w locations).

There's no need to update when your system is working fine and you don't wanna be on bleeding edge versions. The graphical picker was never enabled but in the past I did have the required files for it in the EFI (resource folder and opencanopy). Those files are removed to make downloads quite a bit smaller. My idea is to provide a EFI that works on these machines thats minimal yet has all functionality to get things going. 

I did add a section to the readme on how to setup the graphical picker but disabled by default for the same reason verbose boot is on by default. When installing it's important to see what's going on. Once things are setup and you know it works and how it works you can disable verbose boot, enable graphical picker (or disable it all together and only make it show when holding down alt).

Updating your existing EFI should look a bit like this;

- Download new EFI
- Migrate new fields to your config entries (only graphical options/serials in your case I think)
- Migrate your port map (simply replace it)

The config file still changes often in OpenCore, fields get added or removed or renamed. I like keeping track of it but it's not a requirement to keep your EFI up to date. If it works then it works, no need to change anything unless you want to keep up to date or try Big Sur beta's. At some point the fields in the OpenCore config won't change as often anymore.

Alternatively you can diff the current config with your own and migrate changes that way. 

If you're ok with some shell scripting you could semi-automate the process with a script that applies your changes and changes the serials and such;
https://github.com/zearp/OptiHack/issues/22#issuecomment-707320420

**Comment by davidAlaBer** [comment]
Hi!
Now it works!
For some reason usbports.kext was set to false. Something got messed in the config. 
Thanks!

**Comment by zearp** [comment]
Ohh thats odd. Luckily it was something minor!
