### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by GCPDetective** [zearp/OptiHack#3]
Sorry about posting this as another issue, but I don't know of any other way to get in contact with you lol. Wanted to make a donation for all your hard work and for writing up such a great guide with so much useful information. Is there somewhere I can do this?

**Comment by zearp** [comment]
Nope! This is purely for fun and edutainment. See how deep this rabbit hole goes. But I'm glad it's helpful and useful to you which is a donation in and on itself. Happy hacking!
