### ISSUE TITLE
Supports 7010?

### ISSUE THREAD

**Issue by The1PRimeYT** [zearp/OptiHack#30]
Can I use this for optiplex 7010? or is it kind of diffrent?

**Comment by zearp** [comment]
The 7010 is a different generation. Different chipsets and processor. It won’t work. It can run Catalina but the EFI here is useless for it. 

Though some things are the same. Like dissecting the BIOS to find the offsets for CFG Lock and the other stuff. The process is very similar.

Shouldn’t be too hard to get things going if you follow the Dortania guide and info found on this repo. If you put the effort you will succeed. Let me know if you get stuck or run in to any errors. I don’t mind helping those who d on t expect to be spoon fed haha. 

Dells do require some different settings than the guide. For example releasing USB ownership must be enabled and legacy mode must be enabled in the BIOS for sleep.

Good luck!

**Comment by zearp** [comment]
The 7010 is a different generation. Different chipsets and processor. It won’t work. It can run Catalina but the EFI here is useless for it. 

Though some things are the same. Like dissecting the BIOS to find the offsets for CFG Lock and the other stuff. The process is very similar.

Shouldn’t be too hard to get things going if you follow the Dortania guide and info found on this repo. If you put the effort you will succeed. Let me know if you get stuck or run in to any errors. I don’t mind helping those who don’t expect to be spoon fed haha. 

Dells do require some different settings than the guide. For example releasing USB ownership must be enabled and legacy mode must be enabled in the BIOS for sleep.

Good luck!

**Comment by The1PRimeYT** [comment]
Okay today ima start working on the EFI if i get everything to work perfectly ill drop an example EFI for those who may need it, I got my Ryzen system perfectly running fine so ill let you guys know how it goes
