### ISSUE TITLE
iCloud issues since updating OptiHack and reinstalling macOS

### ISSUE THREAD

**Issue by TheRedHugo** [zearp/OptiHack#38]
Hello,
I have a problem regarding macOS. This started to happen since I updated OptiHack(OpenCore) and reinstalling macOS Big Sur. When I try to login into iCloud I get the error "ICLOUD_DEVICE_UNSUPPORTED". I tried changing my Serial/UUID/MLB but I had no luck. 

Could someone please help me?
Thanks :D

**Comment by zearp** [comment]
This is not the right place for this kind of support.

If you tried [these steps](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html) and still can't get things to work I would suggest asking on a forum or [Reddit](https://old.reddit.com/r/hackintosh/).

Make sure your generated serial comes back as invalid when testing it with Apple's [website](https://checkcoverage.apple.com), have set the ROM value to you ethernet mac address and it should work.

It may help to remove any old computers/installs from iCloud. I changed my serial a couple of times on a test machine and ended up with like 7 iMacs listed there it caused issues at some point. Also clear NVRAM when you change serials, some iCloud related things are kept in there. Wiping it can prevent odd issues.

Good luck!
