### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by BrunoGM** [zearp/OptiHack#39]
Microphone doesn't work on either the front or back ports. The speakers and internal speaker work perfectly tho.

I have tried all the other possible alc ids, 13, 15 and 16, neither of those solved the problem.

In the input settings I have 2 line in options, one of them doesn't give any feedback, while the other just crackling noises. Any idea on how to solve this?
![audio](https://user-images.githubusercontent.com/12564741/110365481-dcb51e00-8023-11eb-88b1-c5e2748f6145.png)

**Comment by davidAlaBer** [comment]
I remember to have crackling and issues on this. I ended up using a usb headset or my webcam micro (logitech).

**Comment by zearp** [comment]
Is it a combo jack? Because I'm quite sure these Dells don't support those. You need ones with separate (green/pink) plugs.

**Comment by zearp** [comment]
I'm using 16 normally cuz of auto-sensing and line-in level input on the front. In 17 the front input applies too much amplification. Which is required for those headset mics nut ill distort normaal line-leven audio. If your headset has separate plugs for the mic and headphone parts it should work good in 17. The inputs on the back don't work in 16 or 17. I don't recall if they worked in other layouts. I'll try to see if I can dig up the posts about the custom layout.

**Comment by zearp** [comment]
https://github.com/zearp/OptiHack/pull/15

**Comment by zearp** [comment]
More info in the link above and here: https://github.com/acidanthera/AppleALC/pull/591

**Comment by BrunoGM** [comment]
Yes, it’s not a combo jack, I use the green and pink(blue on the rear) ports. I checked out the others issues about mics but nobody has a solution(or even the issue) apparently.

**Comment by zearp** [comment]
I don't have any of those to test with myself unfortunately. I've just tried line input from my phone into the front inputs and it sounds fine on 16 but distorted on 17. My guess is that on 17 it applies amplification for (headset mics). Since trs line-in works your plug should work too, is it a normal trs or a mono? 

I'll dig in my cable crate but I don't think I have any mono cables to test with. It would be weird but possible the ports on the Dell don't take mono ones too but trs. In the worst case you could buy a cheap usb audio interface with some in and outputs. macOS supports most usb audio standards, don't go too cheap though.

**Comment by BrunoGM** [comment]
It’s a normal trs plug. If I can’t fix it I m going to buy an usb sound card indeed.

**Comment by zearp** [comment]
Played around with some other layouts just now and I have to say the input quality is pretty bad on every single layout I tried. Even at low input levels the sound can distort a lot. On my daily driver I only use audio over usb and on this machine it just uses the screens awful builtin speakers. With usb you can have as many in and outputs as you need and route them with builtin tools or external ones like Sound Flower.

I don't know what you intend to use the mic for, but I would suggest getting one those "podcast" ones that have both usb and normal wired connections. They will sound a lot better than headset mics and routing the audio over usb will give you better quality and routing options too. Specially with things like a DAW or OBS or Audio Hijack.

**Comment by BrunoGM** [comment]
Thank you a lot for the suggestions. Well, its not that the quality is bad, here it isn't even working at all, but I guess I will just jump to using USB and solve both problems at once. 

The mic would be just for casual use, I ll probably try getting some good USB audio interface as you suggested earlier. If you have any model in mind that you would recommend, I will appreciate hearing about it. Or I might just get a bluetooth headphone as well. Thanks again for the help.

**Comment by zearp** [comment]
Bluetooth latency is terrible for making calls and macOS does not support the new AptX Adaptive or Low Latency variants. If I would only need a mic I'd get a usb mic. A whole audio interface might be overkill and a good one is quite expensive.

I would take a modular approach to upgrading the audio chain. First the mic, then if the onboard audio isn't good enough for the output upgrade that. Doing it that way is a lot cheaper. Good audio chips (like the TDA1305T) that were used in very expensive equipment in the past can now be bought for $20 in a [ready made box](https://www.aliexpress.com/item/32962324804.html) that gives a good headphone amp + optical output for your speakers/big amp.

As for interfaces with inputs, anything with good mic inputs wil be prosumer territory with matching prices. Plus the mic inputs on those are way too good to use anything but a proper mic on. Those xlr inputs, most with phantom power. Overkill. Then there's cheap Chinese ones left, they can be hit and miss. Not sure if its worth to gamble on. 

Another option are these tiny dac/amp combo's like Fiio M3 Pro or Shanling Q1. They have great little headphone amps, builtin mics, wifi with Airplay support, multi directional bluetooth and multi directional usb, can also functiol as standalone soundcard/dac or hifi player (sd card) and I will cost around $99. Very good audio quality fo the money.

In that category are many variants and sizes, pretty sure some will also have normal analog inputs, you'd have to dive in that world and discover what suits your needs. There's a whole world of devices from the like of Fiio and Shanling and many others that might suit your needs perfectly.

Sorry for all the text but audio is deep and while I'm not an audiophile I am an enthusiast that enjoys good audio and just last week upgraded some of my gear so my head is still full from all the comparing and research I did haha. I got myself a little Q1 mainly cuz it can both send and receive LDAC bluetooth.

It can be hooked it up to my computer using usb and play my music in LDAC to my Sony headphones. Apple in all their wisdom hasn't added any modern bluetooth audio codecs in macOS. I don't consider AAC and normal AptX sufficient anymore in 2021 lol.

Good luck man, I'm certain you'll be helped with just a good usb mic for now, but hopefully some of the ramblings will help too.

**Comment by zearp** [comment]
Bluetooth latency is terrible for making calls and macOS does not support the new AptX Adaptive or Low Latency variants. If I would only need a mic I'd get a usb mic. A whole audio interface might be overkill and a good one is quite expensive.

I would take a modular approach to upgrading the audio chain. First the mic, then if the onboard audio isn't good enough for the output upgrade that. Doing it that way is a lot cheaper. Good audio chips (like the TDA1305T) that were used in very expensive equipment in the past can now be bought for $20 in a [ready made box](https://www.aliexpress.com/item/32962324804.html) that gives a good headphone amp + optical output for your speakers/big amp.

As for interfaces with inputs, anything with good mic inputs wil be prosumer territory with matching prices. Plus the mic inputs on those are way too good to use anything but a proper mic on. Those xlr inputs, most with phantom power. Overkill. Then there's cheap Chinese ones left, they can be hit and miss. Not sure if its worth to gamble on. 

Another option are these tiny dac/amp combo's like Fiio M3 Pro or Shanling Q1. They have great little headphone amps, builtin mics, wifi with Airplay support, multi directional bluetooth and multi directional usb, can also function as standalone soundcard/dac or hifi player (sd card) and will cost around $99. Very good audio quality for the money.

In that category are many variants and sizes, pretty sure some will also have normal analog inputs, you'd have to dive in that world and discover what suits your needs. There's a whole lot of devices from the likes of Fiio and Shanling and many others that might suit your needs perfectly.

Sorry for all the text but audio is deep and while I'm not an audiophile I am an enthusiast that enjoys good audio and just last week upgraded some of my gear so my head is still full from all the comparing and research I did haha. I got myself a little Q1 mainly cuz it can both send and receive LDAC bluetooth.

It can be hooked it up to my computer using usb and play my music in LDAC to my Sony headphones. Apple in all their wisdom hasn't added any modern bluetooth audio codecs in macOS. I don't consider AAC and normal AptX sufficient anymore in 2021 lol.

Good luck man, I'm certain you'll be helped with just a good usb mic for now, but hopefully some of the ramblings will help too.

**Comment by BrunoGM** [comment]
I m a bit of a noob in regards of audio but wow, your answer helps a lot actually, it was a great read. I ll totally look into a usb mic and keep my eye on one of those TDA1035T boxes for the future since I don't think I would take full advantage of one of those with my current Logitech G230s.
