### ISSUE TITLE
Dell Logo

### ISSUE THREAD

**Issue by GCPDetective** [zearp/OptiHack#5]
Do you happen to know if the Dell logo scales up or down depending on screen size? I was able to put together an Apple logo that is positioned and scaled correctly in comparison to the macOS boot logo on my 24in display. Just not sure if it gets stretched out on a bigger display or whatnot. I've attached the image below if anyone wants to see if that is indeed the case.

[new-logo5.raw.zip](https://github.com/zearp/OptiHack/files/4514521/new-logo5.raw.zip)
![Optiplex 9020 BIOS Logo 5](https://user-images.githubusercontent.com/56003049/79954821-e3f32d80-844b-11ea-82d4-878a82a6310c.png)

**Comment by zearp** [comment]
Good question. I wouldn't have a clue how Dell scales it. The image is 1280x1280 and my guess would be they keep the image scaled the same on same resolutions. All my screens are 1080p so I can't really test my theory.

**Comment by GCPDetective** [comment]
Same :|

**Comment by zearp** [comment]
Thanks! My main issue is that my screen switches very slow when it's rebooting and changing modes. So I rarely see the boot logo unless I boot into Windows. I changed mine to a solid black one. The progress bar can also be modified. A nice challenge for you to get those images to scale and align it just right haha.

**Comment by GCPDetective** [comment]
I was considering going solid black too. Especially after booting back into Windows. Somewhat off putting seeing windows using an Apple logo as a boot screen lmao. Hopefully everything looks ok later today when I test the boot logo on my TV so I can get started on the progress bar.

**Comment by zearp** [comment]
Haha yeah thats true! I exclusively use macOS personally so no issue for me. I'm really a Mac guy that wanted to try a hackintosh build. It has assured me that it is possible to get a machine as stable as a real Mac for little money.

I was kidding about the progress bar, I don't think it is easy. There are several images that make the animation. You'd have to get the frames of the original Apple bar. I'll look up where it's hidden in a bit. The Dell BIOS is a bloody maze.

**Comment by zearp** [comment]
I tried hunting down the progress bar. Extracted every raw section under ```8C8CE578-8A3D-4F1C-9935-896185C32DD3``` but nothing. I'm sure its under that block though. All images are there but the image format might be different. No bitmap images found with progress bar. I'll analyse the files later and see where it's hiding.  I did add the GUIDs for the other images I found in the [BIOS stuff](https://github.com/zearp/OptiHack/blob/master/text/BIOS_STUFF.md#bios-logo) file.

**Comment by zearp** [comment]
Found the progress bar while researching option ROMs. It's at ```76BE1ABF-1E1E-321D-B7F0-9E0984FDDABC```. I have no clue about the file format, but I'm certain that is the the progress bar.

**Comment by GCPDetective** [comment]
Thanks! I’ll check it out later today.

**Comment by GCPDetective** [comment]
Well this is weird. Just tried using my TV and for some reason I don’t get any sort of boot logo. It’s as if I have it set to solid black lol. The progress bar and everything else comes up fine if I tap f12 during boot. Also when booting into windows it doesn’t use the Boot logo either, it falls back to the default blue Windows logo. Might be because I’m using HDMI, but not sure.

**Comment by zearp** [comment]
I tried yours my monitors, looks good here.  You got the alignment spot on! All my screens are 1080p though and none can change resolution in the osd.
