### ISSUE TITLE
iMac 17,1

### ISSUE THREAD

**Issue by kata62** [zearp/OptiHack#51]
Can we use iMac 17,1 instead of Macmini 7,1 and which one is better

**Comment by zearp** [comment]
That iMac is on the Skylake platform. We have Haswell, the only Mac on Haswell getting Monterey is Mac mini 7,1. SMBIOS does a lot of things and it's best practise to use one matching your h/w platform. The best one is always the one that works best for you. Right now we have 3 choices, the Mac mini the current default but by no means required to use. Currently dual screen on Mac mini SMBIOS is problematic but for single screen setups its perfect.
