### ISSUE TITLE
4K/60 on Big Sur with HD4600

### ISSUE THREAD

**Issue by JohnAker33** [zearp/OptiHack#58]
Not an issue just a report that I've got this working by using an Active DP to HDMI 2.0 adapter and an HDMI 2.0 cable. 

https://www.amazon.com/Displayport-Adapter-Display-Gold-Plated-ThinkPad/dp/B086QQT48Y

Using a passive adapter it would never boot properly. I'm using a 43" 4K TV by Hisense. Text looks sharp too. 

![Screen Shot 2021-07-23 at 1 19 52 PM](https://user-images.githubusercontent.com/79269523/126826673-5204f0ae-e05d-45a1-b505-977157e99fae.png)

![Screen Shot 2021-07-23 at 1 21 45 PM](https://user-images.githubusercontent.com/79269523/126826724-5d0a2d48-be06-4891-b0a5-1950e11c23e5.png)

**Comment by zearp** [comment]
Thanks for sharing! Good to know it can work using an active converter. I could use test using a 4k hdmi dummy inside a converter dongle. Which version of macOS are you running? Looks like Big Sur but not sure.

**Comment by zearp** [comment]
Thanks for sharing! Good to know it can work using an active converter. I could only test using a 4k hdmi dummy inside a converter dongle. Which version of macOS are you running? Looks like Big Sur but not sure.

**Comment by JohnAker33** [comment]
Yes, it's Big Sur as in the title. 4K/60 on Big Sur with HD4600

**Comment by zearp** [comment]
I totally missed the title.
