### ISSUE TITLE
Waking screen from sleep issue?

### ISSUE THREAD

**Issue by arminolat** [zearp/OptiHack#59]
Hello again and Happy Monday!

I've been using my new Hackintosh since the day I set it up as my main PC and everything has been working great!

That said, I'm experiencing issues once my screen goes to sleep - if I move my mouse or press a button on my keyboard to wake it takes quite long to wake up. Sometimes my screen simply will not wake up and I have to hard restart the computer. 

Is this a known issue, maybe something I can do to fix it?

Thank you!

**Comment by zearp** [comment]
There are 2 things at "play" here;

1. wake up might need 2 wake-up events, one for machine and one for the screen. A wake up event is moving mouse/pressing key/power button/etc
2. screens not turning on after wake might benefit from enabling force-online. Depending on the version of the repo you use this setting may already be enabled.

I tried 1 the other day (adding acpi-wake-type property to the pci usb controller) and didn't see any improvements but if you want to test I can modify your config and add the property so you can try. As for 2, you'd have to check your config and see if its enabled or not, you can post your config minus your serials/etc and I can check for you.

**Comment by zearp** [comment]
Added acpi wake-up type  to the config for testing: https://github.com/zearp/OptiHack/commit/70f8cfabf90abef60687960e0d729eca6151d09f

Mind you, force-online is disabled in the that config, it may also need to enable it. This setting seems to depend on cable/monitor combos. I only need to enable that for one monitor (Philips brand).

**Comment by zearp** [comment]
Added acpi wake-up type  to the config for testing: https://github.com/zearp/OptiHack/commit/70f8cfabf90abef60687960e0d729eca6151d09f

Mind you, force-online is disabled in the that config, it may also needed to enable that. This setting seems to depend on cable/monitor combos. I only need to enable that for one monitor (Philips brand).

**Comment by zearp** [comment]
There are 2 things at "play" here;

1. wake up might need 2 wake-up events, one for machine and one for the screen. A wake up event is moving mouse/pressing key/power button/etc
2. screens not turning on after wake might benefit from enabling force-online. Depending on the version of the repo you use this setting may already be enabled.

While I don't have the issue myself, my machines wake up form 1 key press, I did read about preventing this the other day (adding acpi-wake-type property to the pci usb controller). If you want to test this I can modify your config and add the property so you can try. As for 2, you'd have to check your config and see if its enabled or not, you can post your config minus your serials/etc and I can check for you.

Added acpi wake-up type  to the config for testing: https://github.com/zearp/OptiHack/commit/70f8cfabf90abef60687960e0d729eca6151d09f

Mind you, force-online is disabled in the that config, it may also needed to enable that. This setting seems to depend on cable/monitor combos. I only need to enable that for one monitor (Philips brand).

> Sometimes my screen simply will not wake up and I have to hard restart the computer.

Please enable screen sharing on your machine so you can can to login from another computer or phone using a VNC client. This way you can see if it crashed or screen not coming on, and also reboot it gracefully.

**Comment by zearp** [comment]
Did any of the fixes work?

**Comment by arminolat** [comment]
Hi!

Sorry for not replying sooner!

I did not have time to try any of the fixes, but after installing 11.5.1 the other day, I noticed the wake feature is more stable and consistent than before. 

I should have some spare time over the weekend to test out your suggestions as well. 

Thanks!

**Comment by zearp** [comment]
No problem, I'll close it for now. Please update here when you do have some time.

On my main 7020 I only need 1 wake event from a usb keyboard to turn on the machine + screen. But it can differ depending on screen and how you wake it up. On my NUCs even with the patches (acpi-wake and force-online) and even when using the power button, some of them still need 2 events before the screen is awake. It's not an exact science this part of hackintosh and depends on more than just the EFI.
