### ISSUE TITLE
ECC RAM

### ISSUE THREAD

**Issue by GCPDetective** [zearp/OptiHack#6]
> I don't think ECC memory works without also fitting the board with a Xeon or something. Server memory is cheap though.

```
0x5184B 		One Of: ECC Support, VarStoreInfo (VarOffset/VarName): 0x27D, VarStore: 0x2, QuestionId: 0x289, Size: 1, Min: 0x0, Max 0x0, Step: 0x0 {05 A6 32 05 33 05 89 02 02 00 7D 02 10 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00}
0x51871 			One Of Option: Disabled, Value (8 bit): 0x0 {09 0E C3 03 00 00 00 00 00 00 00 00 00 00}
0x5187F 			One Of Option: Enabled, Value (8 bit): 0x1 (default) {09 0E C2 03 30 00 01 00 00 00 00 00 00 00}
0x5188D 		End One Of {29 02}
```

I ordered some ECC RAM from eBay to test this out. I’ll report back here after I receive it.

**Comment by zearp** [comment]
I did some checking and your CPU also needs to support it. Mine doesn't according to Intel's Ark. I don't think any non-Xeon supports it. But I could be wrong, Intel has an amazing amount of variation. The cheapest Xeon I found for this socket was [this](https://ark.intel.com/content/www/us/en/ark/products/75052/intel-xeon-processor-e3-1220-v3-8m-cache-3-10-ghz.html) one for $40 on eBay. Don't think it's worth it unless you can get crazy cheap 8GB ECC modules and max out the RAM.

**Comment by GCPDetective** [comment]
I was afraid of that as well, but on thing that did raise my brow was the fact that on Dells official website it states that the Optiplex 9020 MT/SFF requires non-ECC while the Micro version makes no mention of ECC incompatibility. Haven’t looked into it further yet.

```
OptiPlex 9020 (MT, SFF)	4	32Gb	1600MHz (DDR3 Non ECC)
OptiPlex 9020 (USFF Micro)	2	16Gb	1600MHz (DDR3)
```

https://www.dell.com/support/article/en-ly/sln152123/dell-optiplex-memory-compatibility-guide?lang=en

Could be similar to how the 7020 is stated to only support 16GB when in actually it supports 32.

**Comment by zearp** [comment]
There is some software limiting that they do to differentiate models, like most manufactures do. The socket supports Xeon and it will work if your BIOS is up to date. And even if a 1150 socket cpu would be missing it is possible to add support for it with too much hassle. The bigegstdownside for Xeon in hackintosh is no iGPU.

From Dells perspective if you want ECC you gotta buy a higher end model like a Precision. I understand why they do it. Like them claiming the 7020 SFF board has a 3gbit when they're all 6gbit. Tested it myself. Same on my MacBook, Apple claims it only supports 8GB max, but in reality 16GB works fine.

**Comment by GCPDetective** [comment]
Just got the ECC module today and decided to give it a try for shits and giggles lol. As pointed out by you earlier, it doesn’t seem to work. At least not with the Core series.

**Comment by zearp** [comment]
Thanks for the update!

I been checking out some [Haswell Xeons](https://en.wikipedia.org/wiki/Haswell_(microarchitecture)#Server_processors) that fit this socket. There's some real beasts amongst those. Like [this](https://ark.intel.com/content/www/us/en/ark/products/84684/intel-xeon-processor-e7-8880l-v3-45m-cache-2-00-ghz.html) one. Packing 18 cores/36 threads, supports up to 1.5TB of memory but no iGPU on it. Average TDP  115watts. 

Will take apart the BIOS later to check which Xeons are in it already. Imaging picking up one of those core monsters for little money as server hardware is being dumped at low prices. Buying the processor separately is probably more expensive cuz those sellers know what they got and aren't into shifting machines in bulk.

**Comment by GCPDetective** [comment]
18 cores and 36 threads! Jesus Christ, the IGPU can go shaft itself if that’s the case lmao. Should be a great option if you’ve got a dGPU, might even be better with DRM because no IGPU.

**Comment by zearp** [comment]
Yeah a bit overkill unless you're running a bunch of VMs or do a lot of compiling/rendering or something. It is possible to add the microcodes needed for these processors to the BIOS but I don't know if Dell has locked things down. For Xeon workstations Dell wants people to buy from the Precision range. But I've read several forum posts where people had success with Xeons. The entry models won't perform much better than the i5/i7's so not really worth it unless you can get a bargain for a 8 or more core one.
