### ISSUE TITLE
Intermittent Power-On Delay/Doesn't Power-On at All on Optiplex 9020MT

### ISSUE THREAD

**Issue by GCPDetective** [zearp/OptiHack#61]
Anyone else having issues with the 9020 taking about 10-15 seconds to register a power button press and power on? It's either that or having the system not power on at all unless I turn off power to the PSU, then afterwards press the power button at the same time I turn the power back on to the PSU. I've been having the issue for a while but it only happened a few times so it was hard to track down what was causing the problem until recently.

I tried the following but ran into the same issue again and again:

1. Disconnecting everything from the tower except for power, video, keyboard and mouse.
2. Removing any extra hardware from inside the tower like the GPU, Wi-FI/BT, extra RAM modules, etc. Only hardware connected was the motherboard, EVGA PSU w/ adapter, (x1) 8GB RAM module and a SSD.
3. Reset BIOS.
4. Swap PSU.
5. Swap PSU Adapter.
6. Re-flash BIOS.

I was finally able to "resolve" the issue by disabling Deep Sleep Control and blocking sleep (S3 State) in the BIOS. It's more of a band-aid for now and was hoping someone could shed more light on what might be going on.

**Comment by GCPDetective** [comment]
Forgot to add that I have a backup motherboard on hand from a 7020MT and had the same exact issue. Didn't check to see if disabling sleep in BIOS helped resolve the issue on the board as well.

**Comment by zearp** [comment]
Not sure if this is what you mean but delays when pressing power after it was shutdown within the past x minutes is a "feature" of the power supply. You can hear the relay in the power supply switch after a whole turning it on. On all of mine there can be a delay from pressing the power button till it actually switches on. Especially if I had to force shutdown by holding down the power butting in case of a panic or crash. I think it is some kind of safety function. I find it curious you fixed it by disabling a power state S3 (suspend to ram).

**Comment by GCPDetective** [comment]
Yeah I know what you mean, but this is completely different. The tower would be off all night and I go to press the button and no response for almost 15-20 seconds or an a few rare occasions it wouldn't even turn on. I've been using the tower with power state S3 disabled since I last posted about it with no issues, but I'm thinking of trying to track down the cause of the issue again. Only thing I can think of right now is maybe if disabling power state S3 'fixes' the issue then maybe it's some sort of 'communication' issue between the PSU and the mainboard as I am using an aftermarket PSU with an adapter siting between the two.

**Comment by zearp** [comment]
Oh yeah! That would explain it. I would not be surprised if Dell uses some proprietary stuff. But I also have odd power button behaviour from time to time. When pressing it nothing happens for 10-15 seconds and then it turns on. Like you suggested some kind of communication might be going on. Good to know disabling S3 helps fix this for non-standard power supply!
