### ISSUE TITLE
can not eject dvd driver after powering on for some period

### ISSUE THREAD

**Issue by yankedong** [zearp/OptiHack#64]
First, thanks for your excellent work. 

I have Catalina 10.15.7 installed on my Optiplex 9020MT. Everything works perfectly except the CD/DVD driver.  It works fine after I just boot into the OS. But after some time, I don't know how long, it refuses to eject. If I go to 'System Preferences' and click 'CDs & DVDs', then System Preferences freezes.

**Comment by zearp** [comment]
I don't have a DVD player so I can not even begin to try and reproduce this. 

If it's a standard sata drive it should just work normally. Any misbehaviour is likely not due to the EFI but due to compatibility issues with macOS.
