### ISSUE TITLE
Not seeing the OC boot menu with the latest EFI

### ISSUE THREAD

**Issue by JohnAker33** [zearp/OptiHack#66]
I've replaced the 0.7.3 EFI on my Monterey 12.0.1 USB installer with the new 0.7.6 version. The former works and shows the OC boot menu but the latter doesn't give me any boot menu, just a black screen. Is it necessary to use 12.1 instead ? I'm using the 7020 SFF with i5-4570. DP output adapted to HDMI.

**Comment by zearp** [comment]
I don't have this issue myself. Tested on two machines. Try a different DP port and ideally something without conversion. Clean NVRAM for good measure. Make sure there is no other EFI's being loaded or maybe gotten mixed up.

**Comment by JohnAker33** [comment]
Tried the other DP output and switched to an active DP - HDMI adapter. That made no difference. Don't have a monitor with a DP input. The flash drive shows up as UEFI in the Dell BIOS. I'll try re-making the USB installer on a 2.0 drive instead of the 3.0 Adata I'm using. The only other EFI folder on the partition is labeled Big Sur EFI. Your EFI is labeled just "EFI" with no alterations to it.

**Comment by JohnAker33** [comment]
Tried a USB 2.0 drive and get the same result. The 0.7.6 EFI won't present the OC boot menu. Change to the 0.7.3 EFI on the same USB drive and it shows up as expected. Same video connection, same USB port etc.

**Comment by zearp** [comment]
I have tested this on two machines form scratch. I can't reproduce this. Nothing relating to the menu has changed. You can try Upscale setting in the config file, which his new in 0.7.6 but I can't help unless I can reproduce the issues on a unmodified 7020. I have a bunch of these machines and none of them stopped showing the boot menu.

**Comment by zearp** [comment]
I have tested this on two machines from scratch. I can't reproduce this. Nothing relating to the menu has changed. You can try changing the UIScale setting in the config file, which was changed in 0.7.6 but I can't help unless I can reproduce the issues on an unmodified 7020. I have a bunch of these machines and none of them stopped showing the boot menu. It is unfortunate but if I can't reproduce the same issue there's not much I can do but to guess.

@mgrimace do you experience any issues?

**Comment by mgrimace** [comment]
> @mgrimace do you experience any issues?

I'll test this later tonight if I can. I do recall having a strange issue with one stable release where my main partition (Macintosh HD) wasn't showing up in OC picker. We couldn't get it to reproduce on your machines. I was able to resolve the issue by downloading OpenCore manually myself and replacing it in the EFI folder. We never did figure out why it happened, and it never happened again with future releases. 

The only other thing I can think of would be to remove that "big sur EFI" that's on the partition, that seems unusual to me. The only folder I have on my bootable USB is the EFI folder (which is placed on the EFI partition, so mount EFI, then EFI folder, then folder contents).

I'll test on my machine and see if I get anything unusual with OC picker.

**Comment by JohnAker33** [comment]
>  You can try changing the UIScale setting in the config file, which was changed in 0.7.6 but I can't help unless I can reproduce the issues on an unmodified 7020. 
> 
What would I change the UIScale setting to that would help this work. It says it's set to 0 in the config.plist for the latest 0.7.6 EFI folder.

**Comment by mgrimace** [comment]
Tested new stable release, no problem with OC picker on my end. On Monterey 12.1 beta.

**Comment by JohnAker33** [comment]
> Tested new stable release, no problem with OC picker on my end. On Monterey 12.1 beta.

What is UI scale set to in your config.plist ?  UEFI -> Output -> UIscale

**Comment by mgrimace** [comment]
> > Tested new stable release, no problem with OC picker on my end. On Monterey 12.1 beta.
> 
> What is UI scale set to in your config.plist ?

Default, <01>. I have a 4k monitor (DP) and a second 1080p monitor (DP). You could try downloading OC 0.7.6 manually from Dortania releases and replacing OpenCore.efi in the 0.7.6 (not-working) EFI?

**Comment by mgrimace** [comment]
Replacing OpenCore.efi worked for me for a different issue with picker on an earlier release (picker came up but main partition wasn't showing). I think I also replaced the Bootx64.efi as well but I don't honestly remember. Left config, kexts, etc. untouched.

**Comment by JohnAker33** [comment]
> Replacing OpenCore.efi worked for me for a different issue with picker on an earlier release (picker came up but main partition wasn't showing). I think I also replaced the Bootx64.efi as well but I don't honestly remember. Left config, kexts, etc. untouched.

Where do I download OC 0.7.6 manually from Dortania ?

**Comment by zearp** [comment]
It's funny cuz I use the Dortania builds to save some time when compiling. so it should be the exact same file. I wonder what causes the menu to not appear.

**Comment by zearp** [comment]
It's funny cuz I use the Dortania builds to save some time when compiling, it is the exact same file. I wonder what causes the menu to not appear.

**Comment by zearp** [comment]
I only use 1080p screen though.

**Comment by JohnAker33** [comment]
Thanks guys for the help on this. I'll keep trying to figure it out and let you know if I uncover the cause. Gonna take a break and then come back to it later on tomorrow.

**Comment by mgrimace** [comment]
> It's funny cuz I use the Dortania builds to save some time when compiling, it is the exact same file. I wonder what causes the menu to not appear.

Yeah, that was definitely a bizarre case. We x-filed it because it was utterly unreproducible and the 'fix' didn't make any sense (I even sent you the "bad" opencore.efi and it worked fine on your end, but would reliably not-work on mine). Who knows, but if it happens to help here they great! Best of luck @JohnAker33
