### ISSUE TITLE
What may cause AppleKeyStore operationfailed?

### ISSUE THREAD

**Issue by XZJIsme** [zearp/OptiHack#67]
I followed the guidance step by step, but can't boot into the installer.

**Comment by XZJIsme** [comment]
![IMG_2823](https://user-images.githubusercontent.com/30148847/141439557-fca2034f-3023-49d0-bf51-7eb224567459.JPG)
![IMG_2824](https://user-images.githubusercontent.com/30148847/141449020-ac384612-c9c4-4f31-ab25-f9b016211bad.JPG)

**Comment by zearp** [comment]
I'm closing issues.
