### ISSUE TITLE
Solution to blank OC Boot Menu Screen

### ISSUE THREAD

**Issue by JohnAker33** [zearp/OptiHack#68]
Wanted to report back on what the fix was for this on my 7020 SFF desktop. 

All that was required was to enter the SMUUID data into my config.plist. Used GenSMBIOS.
Nothing else was needed. Then the OC boot menu for my USB installer appeared.

**Comment by JohnAker33** [comment]
Here's the link to the Closed Issue:  https://github.com/zearp/OptiHack/issues/66

**Comment by zearp** [comment]
It makes sense it behaves weirdly when there is missing SMBIOS information.
