### ISSUE TITLE
Black screen on build in HP4600 i5 Dell OptiPlex 7020

### ISSUE THREAD

**Issue by nikos83** [zearp/OptiHack#69]
I'm having screen issues - after start computer on DP-vga converter I can see only black screen - monitor is on ( green light is on) but nothing shows.
Downloaded standard EFI folder for 4gen CPU from olarila works ok - so it seems to dp-vga converter works ok. Any ideas what to do what and where to change to get this working please? Thanks

**Comment by zearp** [comment]
Can you post the working frame buffer? I suspect it may have to do with flags. Not having any issues myself using mostly dP -> HDMI converters too.
