### ISSUE TITLE
sidecar

### ISSUE THREAD

**Issue by kata62** [zearp/OptiHack#71]
I am using your EFI with MT optiplex 9020 and with IGPU HD 4600 only also fenvi T919
but there is no sidecar
please advise

**Comment by zearp** [comment]
It should sort of work but it is not supported by Apple on Haswell platforms as far I know.

It works for me when using a cable but the iPad screen flickers a lot. I think the hardware simply doesn't support the correct streaming protocols Apple uses. I was unable make it work properly. Be sure your Dell and iPad are signed in to the same iCloud account too.

I will do some testing with my 2018 iPad when I get the chance and update this issue. I will close it for now but feel free to post updates.

**Comment by zearp** [comment]
Which SMBIOS model are you using? I'm using the Mac mini one.

**Comment by kata62** [comment]
I am using Mac mini 7,1 but there is no icons for side car in the settings

**Comment by zearp** [comment]
Well [FeatureUnlock](https://github.com/acidanthera/FeatureUnlock) should unlock it when using that SMBIOS. If the kext is loaded then there might be a bug in that kext. You can try some other Sidecar enablers out there.

Just remember that even if you patch/enable it it will not work properly, the screen will flicker. Sidecar is unusable.

Good luck.

**Comment by zearp** [comment]
Just tried it on my test machine, Sidecar works for me. Open display settings and click the add display drop down, your iPad should be listed. My iPad is called "tablet" and the other entry is my Apple TV.

![Screen Shot 2022-04-09 at 12 31 25](https://user-images.githubusercontent.com/63272687/162568186-4f8535e5-603e-45b5-a13a-240ef2b36781.png)

**Comment by kata62** [comment]
yes you are right its there.
thanks.
