### ISSUE TITLE
CFG Lock on an  OptiPlex 9020 AIO

### ISSUE THREAD

**Issue by james090500** [zearp/OptiHack#72]
Hi, I have an OptiPlex 9020 AIO, just thought i'd mention the CFG Lock value is slightly different.

https://zearp.github.io/OptiHack/OptiGuide/installation.html#disable-cfg-lock

It's `0xDAF`. Might be useful to add :) Apart from that guide was flawless. 

```
Setting: CFG lock, Variable: 0xDAF {05 A6 37 01 38 01 51 00 02 00 AF 0D 10 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00}
	Option: Disabled, Value: 0x0 {09 0E F4 00 00 00 00 00 00 00 00 00 00 00}
	Option: Enabled, Value: 0x1 {09 0E F3 00 30 00 01 00 00 00 00 00 00 00}
End of Options {29 02}
```

**Comment by zearp** [comment]
Thanks, I think the guide only has the offsets for the 7020 model. The 9020 uses a different bios and the variants might do to. It could be clearer that everybody should really check their bios dump themselves to be sure. Though revering from bad setting isn't the end of the world. I'll see if I can make it more clear and maybe add a table with the offset for each model/bios.

**Comment by james090500** [comment]
I did discover that a "Load Defaults" didn't actually reset this for me. I had to use a jumper on the board. CMOS battery removal might also work but didn't test.

**Comment by zearp** [comment]
I've documented how to clear all the edits in the guide.

https://zearp.github.io/OptiHack/OptiGuide/troubleshooting.html#resetting-uefibios-completely
