### ISSUE TITLE
Dell 9020 Ventura - Display HD4600 shows 7 MB - How to Fix.

### ISSUE THREAD

**Issue by apsathyan32** [zearp/OptiHack#78]
Thanks for this wonderful work. I have installed Ventura on my Dell 9020 without any issue. HD4600 shows 7 MB. Everything works except Audio Line in for Siri stuff and USB Bluetooth dongle shows with a cross and refuses to turn ON. I was using this Bluetooth dongle till Monterey. Is there any fix to rectify the above said issues. If you can send any link I can follow and I will be happy to learn and do it. Thanks again for this effort you have taken. Cheers.

**Comment by zearp** [comment]
I don't know why the HD4600 frame buffer settings show 7MB for you. You didnt' attach any files or provided any details that would allow me to help you.

**Comment by zearp** [comment]
I don't know why the HD4600 frame buffer settings show 7MB for you. You didn't attach any files or provided any details that would allow me to help you.
